
set pwd   [pwd]
set dir_out  "$pwd/output/$outputName"
set file_list  "$dir_out/$revName.list"
set file_cp  "$dir_out/$revName.cp"
set file_analyze "$dir_out/$revName.analyze"
set file_svf  "$dir_out/$revName.svf"
set file_stamp  "$dir_out/$revName.stamp"
set dir_src  "$dir_out/src"

set file_ddc  "$dir_out/$revName.ddc"
set file_verilog "$dir_out/$revName.v"
set file_cdl "$dir_out/$revName.cdl"
set file_sdc_syn "$dir_out/$revName.syn.sdc"
set file_sdc_pnr "$dir_out/$revName.pnr.sdc"
set file_sdc_pt  "$dir_out/$revName.pt.sdc"
set file_sdf  "$dir_out/$revName.sdf"
set file_report  "$dir_out/$revName.rpt"
set file_report_timing_max  "$dir_out/$revName.timing_max.rpt"
set file_report_timing_min  "$dir_out/$revName.timing_min.rpt"
set file_change_name "$dir_out/$revName.change_names"
set file_check_design "$dir_out/$revName.check_design"
set file_check_timing "$dir_out/$revName.check_timing"
set file_rpt_constraint "$dir_out/$revName.report_constraint"
#set file_check  "$dir_out/$revName.check"
set file_io  "$dir_out/$revName.io"
set file_verilog_with_power "$dir_out/$revName.pwr.v"
